export const CANVAS_CONFIG = {
  BASE_WIDTH: 2000,
  BASE_HEIGHT: 2000,
  BACKGROUND_COLOR: '#0a1929',
  BACKGROUND_R: 10,
  BACKGROUND_G: 25,
  BACKGROUND_B: 41,
  BACKGROUND_TOLERANCE: 15,
  MIN_ALPHA: 10,
} as const;

export const ZOOM_CONFIG = {
  MIN: 0.1,
  MAX: 2.0,
  STEP: 0.1,
  DEFAULT: 0.2,
} as const;

export const BRUSH_CONFIG = {
  MIN_SIZE: 1,
  MAX_SIZE: 50,
  DEFAULT_COLOR: '#ffffff',
  DEFAULT_SIZE: 20,
} as const;

export const SNOWFLAKE_CONFIG = {
  BORDER_PADDING: 50,
  MIN_FALL_SPEED: 30,
  MAX_FALL_SPEED: 70,
  MIN_DRIFT_SPEED: -10,
  MAX_DRIFT_SPEED: 10,
  SPAWN_Y_OFFSET: -100,
  SPAWN_Y_RANDOM: 50,
  RESET_Y_OFFSET: -100,
  RESET_Y_RANDOM: 50,
  RESET_X_MARGIN: 0.1,
  RESET_X_RANGE: 0.8,
  MAX_SIZE: 200,
  ROTATION_SPEED: 30,
  DRIFT_FREQUENCY: 0.3,
  VISIBILITY_MARGIN: 200,
  RESET_BOTTOM_OFFSET: 100,
  FULL_ROTATION: 360,
  PI_MULTIPLIER: Math.PI * 2,
  MAX_SNOWFLAKES_ON_TREE: 50,
} as const;

export const ANALYSIS_CONFIG = {
  SAMPLE_STEP_SMALL: 2,
  SAMPLE_STEP_LARGE: 4,
  LARGE_CANVAS_THRESHOLD: 1000,
  COVERAGE_MULTIPLIER: 1000,
  SYMMETRY_WEIGHT: 0.6,
  STRUCTURE_WEIGHT: 0.25,
  COVERAGE_WEIGHT: 0.15,
  BRIGHTNESS_THRESHOLD: 200,
  BRIGHTNESS_BONUS: 10,
  MIN_MEANINGFUL_PIXELS: 5,
  UPDATE_INTERVAL: 500,
  IDLE_TIMEOUT: 200,
  INITIAL_DELAY: 300,
  STROKE_END_DELAY: 50,
  BACKGROUND_TOLERANCE_SMALL: 5,
  CANVAS_WIDTH: 2000,
  CANVAS_HEIGHT: 2000,
  EXTRACT_PADDING: 10,
  MIN_CANVAS_SIZE: 1,
} as const;

export const TREE_CONFIG = {
  WIDTH_RATIO: 0.6,
  MAX_WIDTH: 400,
  HEIGHT_RATIO: 0.75,
  TOP_OFFSET: 0.05,
  TRUNK_HEIGHT_RATIO: 0.15,
  TRUNK_WIDTH: 30,
  TREE_COLOR: '#2d5016',
  TRUNK_COLOR: '#8b4513',
  GARLAND_COLOR: '#4a4a4a',
  GARLAND_WIDTH: 2,
  LIGHT_COLORS: [
    '#FF0000',
    '#00FF00',
    '#0000FF',
    '#FFFF00',
    '#FF00FF',
    '#00FFFF',
    '#FFA500',
  ],
  LIGHT_RADIUS: 15,
  LIGHT_BULB_RADIUS: 6,
  LIGHT_HIGHLIGHT_RADIUS: 2,
  LIGHT_HIGHLIGHT_OFFSET: 2,
  LIGHT_OPACITY: 0.6,
  ORNAMENT_COLORS: [
    '#FF0000',
    '#0000FF',
    '#FFFF00',
    '#FF00FF',
    '#00FF00',
    '#FFA500',
  ],
  ORNAMENT_SIZES: [11, 12, 13],
  FIXED_SNOWFLAKE_SIZE_ON_TREE: 36,
  ORNAMENT_CAP_RADIUS: 3,
  ORNAMENT_CAP_WIDTH: 6,
  ORNAMENT_CAP_HEIGHT: 4,
  ORNAMENT_SHADOW_RATIO: 0.7,
  ORNAMENT_HIGHLIGHT_RATIO: 0.3,
  ORNAMENT_SHADOW_OPACITY: 0.3,
  ORNAMENT_GRADIENT_STOP_1: 0,
  ORNAMENT_GRADIENT_STOP_2: 0.3,
  ORNAMENT_GRADIENT_STOP_3: 1,
  ORNAMENT_WHITE: '#FFFFFF',
  ORNAMENT_BLACK: '#000000',
  ORNAMENT_CAP_COLOR: '#FFD700',
  ANIMATION_TIME_RESET: 1000,
  LIGHT_ANIMATION_MULTIPLIER: 2,
} as const;

export const ANIMATION_CONFIG = {
  MIN_SPEED: 0,
  MAX_SPEED: 2,
  DEFAULT_SPEED: 1,
  LIGHT_ANIMATION_DURATION: 2,
  LIGHT_DELAY_STEP: 0.2,
} as const;

export const API_CONFIG = {
  DEFAULT_URL: '/api',
} as const;

export const HEADER_CONFIG = {
  GRADIENT_START: '#0a1929',
  GRADIENT_MID: '#1a2332',
  GRADIENT_END: '#0f1b2e',
  TEXT_GRADIENT_START: '#81d4fa',
  TEXT_GRADIENT_MID: '#ffffff',
  TEXT_GRADIENT_END: '#c0c0c0',
  TEXT_COLOR: '#b0bec5',
} as const;

export const UI_CONFIG = {
  CANVAS_HEIGHT: 600,
  MAX_PAPER_WIDTH: 900,
  SIMILARITY_HIGH: 50,
  SIMILARITY_MEDIUM: 25,
  COLOR_HIGH: '#4caf50',
  COLOR_MEDIUM: '#ff9800',
  COLOR_LOW: '#f44336',
  BUTTON_MIN_WIDTH: 200,
  BUTTON_PADDING: '12px 24px',
  BUTTON_FONT_SIZE: '1.1rem',
  DRAW_TAB_INDEX: 0,
  TREE_TAB_INDEX: 1,
  APP_BACKGROUND_COLOR: '#0a1929',
} as const;
